#Each new term in the Fibonacci sequence is 
#generated by adding the previous two terms. 

#By considering the terms in the Fibonacci sequence whose values do not 
#exceed four million, find the sum of the even-valued terms.
fibonacci_even = []
f_n = 1
f_n1 = 2
f_n2 = 3


while f_n2 < 4000000:
  # if fn_2 % 2 == 0:
      #fibonacci_even.append(fn_2)
  # f_n2 = fn + f_n1
  #
  #
  #
  print(sum(fibonacci_even))
